openapi: 3.0.4

info:
  title: Algashop - Ordering
  version: 1.0.0

servers:
  - description: Development
    url: http://localhost:8080
  - description: Production
    url: https://api.algashop.com

paths:
  /api/v1/customers:
    post:
      description: Register a new customer
      tags:
        - Customers
    get:
      description: List Customers
      tags:
        - Customers
  /api/v1/customers/{customerId}:
    get:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: 'e6e4f7e9-4e9e-4d5d-9e6e-7e9e4f7e9e4f'
      description: Get a single customer by id
      tags:
        - Customers
    put:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: 'e6e4f7e9-4e9e-4d5d-9e6e-7e9e4f7e9e4f'
      description: Edit customer
      tags:
        - Customers
    delete:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: 'e6e4f7e9-4e9e-4d5d-9e6e-7e9e4f7e9e4f'
      description: Delete customer
      tags:
        - Customers


